### ISSUE TITLE
Неправильные кода возврата

### ISSUE THREAD

**Issue by llirik42** [Concerts-Mate/Elastic-Service#10]
# Описание
При поиске городов по имени сервис возвращает неправильные коды возврата.

# Воспроизведение
Запустить Users-Service, добавить любому пользователю (даже не зарегестрированному) города
- Искитим (код должен быть `SUCCESS_CITY`, а он `FUZZY_CITY`)
- Москва (код должен быть `SUCCESS_CITY`, а он `FUZZY_CITY`)
- мАсква (код должен быть `FUZZY_CITY`, а он `EMPTY`)
- 123 (код должен быть `EMPTY`, а он `INTERNAL_ERROR`)

**Comment by dura0ok** [comment]
Проблема была в том, что значения в енаме для всего прото файла должны быть уникальны
Решили вместе с @llirik42
