### ISSUE TITLE
Тесты. Срок - 19.04

### ISSUE THREAD

**Issue by llirik42** [Concerts-Mate/Elastic-Service#3]
Добавить как минимум такие тесты:
- Проверить что ищется по четкому поиску Москва
- Проверить что ищется по нечеткому поиску “Масква”
- Проверить что ищется по координатам(lat, lon) Москва в радиусе 10км

В конце расписать все тесты подробно (что и как проверяется)

**Comment by llirik42** [comment]
@dura0ok

**Comment by llirik42** [comment]
@dura0ok, что с issue?

**Comment by llirik42** [comment]
Почему просрочил и никому не сообщил?

**Comment by llirik42** [comment]
Issue продливается до 29.04, но начислены штрафные балы

**Comment by dura0ok** [comment]
### Написанные тесты находятся в пакете `internal`

1. **TestSearchMoscowExists**:
   - Проверяет, что поиск по имени "Москва" возвращает хотя бы один результат.

2. **TestSearchMoscowFirstFoundCorrect**:
   - Проверяет, что первый найденный результат поиска по имени "Москва" соответствует ожидаемому имени.

3. **TestSearchMoscowFuzzy**:
   - Проверяет, что даже при небольших опечатках (например, "Масква" вместо "Москва") поиск все равно находит правильный результат.

4. **TestSearchMoscowByCoords**:
   - Проверяет, что поиск по координатам Москвы возвращает хотя бы один результат и Москва присутствует в результатах.

5. **TestSearchNonExistentCityByName**:
   - Проверяет, что поиск по несуществующему названию города возвращает пустой результат.

6. **TestSearchByNonExistentCoords**:
   - Проверяет, что поиск по несуществующим координатам возвращает пустой результат.

7. **TestConstructorValidation**:
   - Проверяет, что конструктор для создания координат выдает ошибку при передаче недопустимых значений координат.
